### ISSUE TITLE
Error when moving Library to S3 storage and deleting

### ISSUE THREAD

**Issue by nexuschurch** [Sitefinity/amazon-s3-provider#4]
When you try to move a library to the S3 storage provider or when you delete a object that is residing in S3 you get an error:

Method not found: 'System.IAsyncResult Amazon.S3.IAmazonS3.BeginDeleteObject(Amazon.S3.Model.DeleteObjectRequest, System.AsyncCallback, System.Object)'.

**Comment by VesselinVassilev** [comment]
Try using this in the Delete method of the provider:

transferUtility.S3Client.DeleteObject(request);

**Comment by bonny-bonev** [comment]
Fixed for Sitefinity 8.2
